"""empty message

Revision ID: 5ab0f8e3b488
Revises: a53524410b9f
Create Date: 2019-12-03 15:05:44.175224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab0f8e3b488'
down_revision = 'a53524410b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_possible_moves')
    op.drop_table('possible_move')
    op.add_column('move', sa.Column('list_id', sa.Unicode(), nullable=True))
    op.create_foreign_key(None, 'move', 'possible_moves', ['list_id'], ['id'])
    op.drop_column('move', 'possible_moves_id')
    op.drop_column('move', 'possible_move_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move', sa.Column('possible_move_id', sa.VARCHAR(), nullable=True))
    op.add_column('move', sa.Column('possible_moves_id', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'move', type_='foreignkey')
    op.drop_column('move', 'list_id')
    op.create_table('possible_move',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_position', sa.VARCHAR(), nullable=True),
    sa.Column('target_position', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['chess_game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_possible_moves',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.VARCHAR(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
