"""empty message

Revision ID: d9a091d1ce2b
Revises: 5ab0f8e3b488
Create Date: 2019-12-03 15:19:23.519674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a091d1ce2b'
down_revision = '5ab0f8e3b488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'move', 'possible_moves', ['list_id'], ['id'])
    op.drop_column('move', 'possible_move_id')
    op.drop_column('move', 'possible_moves_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move', sa.Column('possible_moves_id', sa.VARCHAR(), nullable=True))
    op.add_column('move', sa.Column('possible_move_id', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'move', type_='foreignkey')
    # ### end Alembic commands ###
